/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gcms.forms.panels;

/**
 * The Golf Course Management System (GCMS) enables employees of a golf course
 * to perform daily tasks such as completing transactions, storing employee and
 * member information, and scheduling grounds work.
 * 
 * This project has been designed and developed for course CIS4810 Systems
 * Development Project taught by Professor Mary Garrett. Project Team 1 consists
 * of the following team members: Michael Abbotts, Baron Amman, Ryan Cipullo,
 * Solomon Colley, and David Ward.
 * 
 * @author Solomon Colley
 * @see SDD for more information on system design and documentation
 * @since 9/23/2019
 * @version 1.0
 */
public class HowToPanel extends javax.swing.JPanel {
    /**
     * Creates new form HowToPanel
     */
    public HowToPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        howToScrollPane = new javax.swing.JScrollPane();
        howToTextArea = new javax.swing.JTextArea();

        howToScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        howToScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        howToScrollPane.setFocusable(false);
        howToScrollPane.setOpaque(false);

        howToTextArea.setEditable(false);
        howToTextArea.setColumns(20);
        howToTextArea.setLineWrap(true);
        howToTextArea.setRows(5);
        howToTextArea.setText("The GCMS follows a  create, read, update and delete design. The following describes how to use each function in the GCMS according to its design:\n\nCreate - With a table loaded, click the 'New row' button to add one or more  new rows at the end of the table. Fill out the necessary cells. Once the row(s) are filled out appropriately, highlight row(s) and click the 'Create' button. This adds the highlighted row(s) to the database.\n\nRead - With a table selected in the drop down menu, click the 'Read' button to load (or reload) a database table into the UI table.\n\nUpdate - With a table loaded, change any row(s) by double-clicking in a cell and using the 'Tab' key on you keyboard to tab through other cells one by one. Once the row(s) reflect the changes you want, highlight the changed row(s) and click the 'Update' button.\n\nDelete - With a table loaded, highlight any or all rows in a table and click the 'Delete' button. The selected row(s) will be deleted permanently from the database.\n\nThe database will always reflect the changes you make, but it may be necessary to click the 'Read' button after creating, updating, or deleting records for the UI table to reflect those changes.");
        howToTextArea.setWrapStyleWord(true);
        howToTextArea.setBorder(null);
        howToTextArea.setFocusable(false);
        howToTextArea.setOpaque(false);
        howToScrollPane.setViewportView(howToTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howToScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(howToScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane howToScrollPane;
    private javax.swing.JTextArea howToTextArea;
    // End of variables declaration//GEN-END:variables
} // end HowToPanel
